export const listData = [
    {
      id: 1,
      title_en: "Related Group DRG System",
      img: "https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '25',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.', 
      date_details: "13 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "456 Park Avenue, London",
      latitude: 51.5074,
      longitude: -0.1278,
    },
    {
      id: 2,
      title_en: "Related Group DRG System",
      img: "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '25',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "13 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "789 Oxford Street, London",
      latitude: 52.4862,
      longitude: -1.8904,
    },
    {
      id: 3,
      title_en: "Related Group DRG System",
      img: "https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '25',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "13 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "101 Baker Street, London",
      latitude: 53.4808,
      longitude: -2.2426,
    },
    {
      id: 4,
      title_en: "Related Group DRG System",
      img: "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '25',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "13 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "234 Kingsway, London,",
      latitude: 53.8008,
      longitude: -1.5491,
    },
    {
      id: 5,
      title_en: "Related Group DRG System",      
      img: "https://images.pexels.com/photos/276625/pexels-photo-276625.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '25',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "13 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "567 Victoria Road, London",
      latitude: 53.4084,
      longitude: -2.9916,
    },
    {
      id: 6,
      title_en: "Related Group DRG System",
      img: "https://images.pexels.com/photos/271816/pexels-photo-271816.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '25',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "14 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "890 Regent Street, London",
      latitude: 54.9783,
      longitude: -1.6174,
    },
    {
      id: 7,
      title_en: "Related Group DRG System",
      img: "https://images.pexels.com/photos/2029667/pexels-photo-2029667.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '25',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "14 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "112 Piccadilly, London",
      latitude: 53.3811,
      longitude: -1.4701,
    },
    {
      id: 8,
      title_en: "Related Group DRG System",
      img: "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '25',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "14 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "8765 Main High Street, London",
      latitude: 51.4545,
      longitude: -2.5879,
    },
    {
      id: 9,
      title_en: "Related Group DRG System",
      img: "https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '25',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "14 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "456 Park Avenue, London",
      latitude: 51.5074,
      longitude: -0.1278,
    },
    {
      id: 10,
      title_en: "Related Group DRG System",
      img: "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '25',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "14 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "789 Oxford Street, London",
      latitude: 52.4862,
      longitude: -1.8904,
    },
    {
      id: 11,
      title_en: "Clinical documentation improvement and ACDIS CDI Apprenticeship",
      img: "https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '30',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "15 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "101 Baker Street, London",
      latitude: 53.4808,
      longitude: -2.2426,
    },
    {
      id: 12,
      title_en: "Clinical documentation improvement and ACDIS CDI Apprenticeship",
      img: "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '30',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "15 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "234 Kingsway, London,",
      latitude: 53.8008,
      longitude: -1.5491,
    },
    {
      id: 13,
      title_en: "Clinical documentation improvement and ACDIS CDI Apprenticeship",      
      img: "https://images.pexels.com/photos/276625/pexels-photo-276625.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '30',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "15 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "567 Victoria Road, London",
      latitude: 53.4084,
      longitude: -2.9916,
    },
    {
      id: 14,
      title_en: "Clinical documentation improvement and ACDIS CDI Apprenticeship",
      img: "https://images.pexels.com/photos/271816/pexels-photo-271816.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '30',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "15 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "890 Regent Street, London",
      latitude: 54.9783,
      longitude: -1.6174,
    },
    {
      id: 15,
      title_en: "Clinical documentation improvement and ACDIS CDI Apprenticeship",
      img: "https://images.pexels.com/photos/2029667/pexels-photo-2029667.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '30',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "15 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "112 Piccadilly, London",
      latitude: 53.3811,
      longitude: -1.4701,
    },
    {
      id: 16,
      title_en: "Clinical documentation improvement and ACDIS CDI Apprenticeship",
      img: "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '30',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "16 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "8765 Main High Street, London",
      latitude: 51.4545,
      longitude: -2.5879,
    },
    {
      id: 17,
      title_en: "Clinical documentation improvement and ACDIS CDI Apprenticeship",
      img: "https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '30',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "16 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "456 Park Avenue, London",
      latitude: 51.5074,
      longitude: -0.1278,
    },
    {
      id: 18,
      title_en: "Clinical documentation improvement and ACDIS CDI Apprenticeship",
      img: "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '30',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "16 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "789 Oxford Street, London",
      latitude: 52.4862,
      longitude: -1.8904,
    },
    {
      id: 19,
      title_en: "Clinical documentation improvement and ACDIS CDI Apprenticeship",
      img: "https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '30',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "16 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "101 Baker Street, London",
      latitude: 53.4808,
      longitude: -2.2426,
    },
    {
      id: 20,
      title_en: "Clinical documentation improvement and ACDIS CDI Apprenticeship",
      img: "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '30',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "16 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "234 Kingsway, London,",
      latitude: 53.8008,
      longitude: -1.5491,
    },
    {
      id: 21,
      title_en: "Medical Coding and Diagnosis",      
      img: "https://images.pexels.com/photos/276625/pexels-photo-276625.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '30',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "17 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "567 Victoria Road, London",
      latitude: 53.4084,
      longitude: -2.9916,
    },
    {
      id: 22,
      title_en: "Medical Coding and Diagnosis",
      img: "https://images.pexels.com/photos/271816/pexels-photo-271816.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '30',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "17 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "890 Regent Street, London",
      latitude: 54.9783,
      longitude: -1.6174,
    },
    {
      id: 23,
      title_en: "Medical Coding and Diagnosis",
      img: "https://images.pexels.com/photos/2029667/pexels-photo-2029667.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '30',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "17 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "112 Piccadilly, London",
      latitude: 53.3811,
      longitude: -1.4701,
    },
    {
      id: 24,
      title_en: "Medical Coding and Diagnosis",
      img: "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '30',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "17 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "8765 Main High Street, London",
      latitude: 51.4545,
      longitude: -2.5879,
    },
    {
      id: 25,
      title_en: "Medical Coding and Diagnosis",
      img: "https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '30',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "17 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "456 Park Avenue, London",
      latitude: 51.5074,
      longitude: -0.1278,
    },
    {
      id: 26,
      title_en: "Medical Coding and Diagnosis",
      img: "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '30',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "18 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "789 Oxford Street, London",
      latitude: 52.4862,
      longitude: -1.8904,
    },
    {
      id: 27,
      title_en: "Medical Coding and Diagnosis",
      img: "https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '30',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "18 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "101 Baker Street, London",
      latitude: 53.4808,
      longitude: -2.2426,
    },
    {
      id: 28,
      title_en: "Medical Coding and Diagnosis",
      img: "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '30',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "18 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "234 Kingsway, London,",
      latitude: 53.8008,
      longitude: -1.5491,
    },
    {
      id: 29,
      title_en: "Medical Coding and Diagnosis",      
      img: "https://images.pexels.com/photos/276625/pexels-photo-276625.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '30',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "18 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "567 Victoria Road, London",
      latitude: 53.4084,
      longitude: -2.9916,
    },
    {
      id: 30,
      title_en: "Medical Coding and Diagnosis",
      img: "https://images.pexels.com/photos/271816/pexels-photo-271816.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '30',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "18 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "890 Regent Street, London",
      latitude: 54.9783,
      longitude: -1.6174,
    },
    {
      id: 31,
      title_en: "Medical Coding and Diagnosis",
      img: "https://images.pexels.com/photos/2029667/pexels-photo-2029667.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '30',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "19 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "112 Piccadilly, London",
      latitude: 53.3811,
      longitude: -1.4701,
    },
    {
      id: 32,
      title_en: "Medical Coding and Diagnosis",
      img: "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '30',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "19 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "8765 Main High Street, London",
      latitude: 51.4545,
      longitude: -2.5879,
    },
    {
      id: 33,
      title_en: "Medical Coding and Diagnosis",
      img: "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '30',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "19 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "8765 Main High Street, London",
      latitude: 51.4545,
      longitude: -2.5879,
    },
    {
      id: 34,
      title_en: "Medical Coding and Diagnosis",
      img: "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '30',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "19 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "8765 Main High Street, London",
      latitude: 51.4545,
      longitude: -2.5879,
    },
    {
      id: 35,
      title_en: "Medical Coding and Diagnosis",
      img: "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      from_time: "10:00 am", 
      code: 'Ih12K',
      user_id: '30',
      short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
      date_details: "19 Aug 2024",
      location: "The Ritz-Carlton, Riyadh",
      address: "8765 Main High Street, London",
      latitude: 51.4545,
      longitude: -2.5879,
    },
  ];
  
  export const singlePostData = {
    id: 1,
    title: "Beautiful Apartment",
    price: 1200,
    images: [
      "https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    bedRooms: 2,
    bathroom: 1,
    size: 861,
    latitude: 51.5074,
    longitude: -0.1278,
    city: "London",
    address: "1234 Broadway St",
    school: "250m away",
    bus: "100m away",
    restaurant: "50m away",
    description:
      "Future alike hill pull picture swim magic chain seed engineer nest outer raise bound easy poetry gain loud weigh me recognize farmer bare danger. actually put square leg vessels earth engine matter key cup indeed body film century shut place environment were stage vertical roof bottom lady function breeze darkness beside tin view local breathe carbon swam declared magnet escape has from pile apart route coffee storm someone hold space use ahead sheep jungle closely natural attached part top grain your grade trade corn salmon trouble new bend most teacher range anybody every seat fifteen eventually",
  };
  
  export const userData = {
    id: 1,
    name: "John Doe",
    img: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  };