export const myaccData = [
    {
      id: 1,
      fname: "Basma",
      lname: "Elokaily",
      img: "https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      email: "basmaelokaily@gmail.com", 
      events:[
        {
          id: 1,
          title_en: "Related Group DRG System",
          img: "https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
          from_time: "10:00 am", 
          code: 'Ih12K',
          short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.', 
          date_details: "3 Jan 2025",
          location: "The Ritz-Carlton, Riyadh",
          address: "456 Park Avenue, London",
          latitude: 51.5074,
          longitude: -0.1278,
        },
        {
          id: 2,
          title_en: "Related Group DRG System",
          img: "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
          from_time: "10:00 am", 
          code: 'Ih12K',
          short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
          date_details: "3 Jan 2025",
          location: "The Ritz-Carlton, Riyadh",
          address: "789 Oxford Street, London",
          latitude: 52.4862,
          longitude: -1.8904,
        },
        {
          id: 3,
          title_en: "Related Group DRG System",
          img: "https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
          from_time: "10:00 am", 
          code: 'Ih12K',
          short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
          date_details: "3 Jan 2025",
          location: "The Ritz-Carlton, Riyadh",
          address: "101 Baker Street, London",
          latitude: 53.4808,
          longitude: -2.2426,
        },
        {
          id: 4,
          title_en: "Related Group DRG System",
          img: "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
          from_time: "10:00 am", 
          code: 'Ih12K',
          short_desc_en: 'Lorem ipsum dolor sit amet, consectere\nadipiscing elit.',
          date_details: "3 Jan 2025",
          location: "The Ritz-Carlton, Riyadh",
          address: "234 Kingsway, London,",
          latitude: 53.8008,
          longitude: -1.5491,
        },
    ]
}
]

